# Generated by Django 4.1.1 on 2022-09-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_comment_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='closed',
        ),
        migrations.AddField(
            model_name='comment',
            name='tag',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], default='DEFAULT', max_length=20),
        ),
    ]
