# Generated by Django 4.1.1 on 2022-10-01 05:27

from django.db import migrations, models


def update_priorities(apps, schema_editor):
    # Update our existing Tickets to conform to the new migration.
    Ticket = apps.get_model('tickets', 'Ticket')
    priority_translation_table = {
        "HIGH": 3,
        "MEDIUM": 2,
        "LOW": 1,
    }
    for ticket in Ticket.objects.all():
        ticket.priority = priority_translation_table[ticket.priority]
        ticket.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_remove_comment_closed_comment_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
        migrations.RunPython(update_priorities),
    ]
